### ISSUE TITLE
메인화면 및 MyPage 구성

### ISSUE THREAD

**Issue by woodencatty** [woodencatty/Mobile2017Proj#2]
각 메뉴를 이어줄 수 있는 메인페이지를 구성해주세요.

메뉴는 지도, 게시판 모두보기, 설정, 마이페이지로 구성해주세요.

마이페이지는 파일 입출력을 사용해서 사용자 정보를 저장할 수 있도록 만들어주세요.

설정은 퍼미션 설정을 통해 필요한 기능을 켜고 끌 수 있게 만들어주세요.

**Comment by elimerins** [comment]
1. 지도클릭시 지도로 넘어갈 수 있게함. 
2. 게시판 모두 보기는 어떤 게시판이 있는지 봐야될거같고
3. 설정은 어떤게 들어가면..?
4. 마이페이지는 페북으로 연동함. 추후 기능 추가

**Comment by woodencatty** [comment]
설정은 사용자 계정 명, 비밀번호같은게 올라가면 될것같아요.

사용자 계정 명(닉네임)을 받아서 저장할 수 있어야해요.
